
version: '3'

services:
  redis:
    image: 'redis:latest'
    networks:
      - demo-network
  python-aef:
    image: python_aef
    networks:
      - demo-network
    hostname: exposer
    container_name: python_aef
    build:
      context: ./python_aef
    volumes:
      - ./python_aef:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REQUESTS_CA_BUNDLE=/usr/src/app/ca.crt
      - SSL_CERT_FILE=/usr/src/app/ca.crt
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
      - CAPIF_PORT=8080
    depends_on:
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
  capif_callback_server:
    build:
      context: ./capif_callback_server
    networks:
      - demo-network
    ports:
      - 8086:8080
    volumes:
      - ./capif_callback_server:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - host.docker.internal:host-gateway


networks:
  demo-network:
    external: true